const mongoose = require('mongoose');

const FormDataSchema = new mongoose.Schema({
  date: String,
  unitName: String,
  designation: String,
//   fullName: { type: String, required: true },
  fullName: String,
  motherName: String,
  fatherName: String,
  presentAddress: String,
  presentAddressLine2: String,
  presentPoliceStation: String,
  permanentAddress: String,
  permanentAddressLine2: String,
  permanentPoliceStation: String,
  mobile1: String,
  mobile2: String,
  height: String,
  weight: String,
  chest: String,
  education: String,
  idMark: String,
  dob: Date,
  age: String,
  maritalStatus: String,
  aadharNo: String,
  voterId: String,
  bankName: String,
  bankAccountNo: String,
  ifscCode: String,
  uan: String,
  esic: String,
  prevCompany: String,
  prevDesignation: String,
  fromDate: Date,
  toDate: Date,
  spouseName: String,
  spouseDob: Date,
  child1: String,
  child2: String,
  emergencyContactName: String,
  emergencyContactMobile: String,
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('FormData', FormDataSchema);
